- name: bug
  color: d73a4a
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: d4b4c2
  description: This will not be worked on

- name: stale
  color: a0a2a3
  description: This issue is stale

- name: component/runtime-sidecar
  color: .inf
  description: Related to the Runtime-sidecar

- name: component/streaming
  color: .inf
  description: Related to the Streaming runner

- name: component/labsdk
  color: 589fa3
  description: Related to the LabSDK

- name: component/historian
  color: .inf
  description: Related to the Historian

- name: provider/snowflake
  color: 29b5e8
  description: Related to the Snowflake provider

- name: provider/aws
  color: ff9900
  description: Related to the AWS provider

- name: provider/redis
  color: 7A0C00
  description: Related to the Redis provider

- name: size/xs
  color: 5eeb34
  description: This PR introduce an extra small change
- name: size/s
  color: 37c3e6
  description: This PR introduce a small change
- name: size/m
  color: 3468eb
  description: This PR introduce a medium change
- name: size/l
  color: d12de0
  description: This PR introduce a large change
- name: size/xl
  color: ed268a
  description: This PR introduce an extra large change
