# permissions for end users to edit featuresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureset-editor-role
rules:
- apiGroups:
  - k8s.raptor.ml
  resources:
  - featuresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.raptor.ml
  resources:
  - featuresets/status
  verbs:
  - get
