# permissions for end users to view featuresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: featureset-viewer-role
rules:
- apiGroups:
  - k8s.raptor.ml
  resources:
  - featuresets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.raptor.ml
  resources:
  - featuresets/status
  verbs:
  - get
