# permissions for end users to view features.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feature-viewer-role
rules:
- apiGroups:
  - k8s.raptor.ml
  resources:
  - features
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.raptor.ml
  resources:
  - features/status
  verbs:
  - get
