# Adds namespace to all resources.
namespace: raptor-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: raptor-

resources:
- ../default

patchesStrategicMerge:
- core_patch.yaml
- historian_patch.yaml
