---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-core
    app.kubernetes.io/part-of: raptor
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-core
  namespace: system
  labels:
    control-plane: controller-core
spec:
  selector:
    matchLabels:
      control-plane: controller-core
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: core
      labels:
        control-plane: controller-core
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: core
        command:
        - /core
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        image: controller:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 60000
          name: http
        - containerPort: 60001
          name: grpc
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      serviceAccountName: controller-core
      terminationGracePeriodSeconds: 10
