name: Lint

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:

  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - name: Clone the code
      uses: actions/checkout@v3
    - name: Cache go dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest          # Always uses the latest patch version.
        only-new-issues: true   # Show only new issues if it's a pull request
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=5m
    - name: Report failure
      if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-issue
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 🐛 Lint failed for ${{ github.sha }}
        body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        labels: bug
